version: '3.9'

volumes:
  postgres_data:                                 # <- Rename "volume_name"
    name: postgres_data   

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    container_name: postgres
    environment:
    - POSTGRES_USER=${PGUSER}
    - POSTGRES_PASSWORD=${PGPASSWORD}
    - POSTGRES_DB=${PGDATABASE}
    ports:
      - "5432:5432"
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$PGUSER\" -d \"$$DB_NAME\""
      timeout: 2s
    volumes:
      - postgres_data:/var/lib/postgresql/data
