# Generated by Django 4.2.7 on 2023-12-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_alter_profil_profil_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='profil_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/profil_pictures/'),
        ),
    ]
