# Generated by Django 4.2.7 on 2023-12-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_alter_profil_profil_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='static/media/cv/'),
        ),
        migrations.AddField(
            model_name='profil',
            name='cv_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/cv_pictures/'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
