# Generated by Django 4.2.7 on 2023-12-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_profil_cv_profil_cv_picture_alter_profil_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True),
        ),
    ]
