# Generated by Django 4.2.7 on 2023-12-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_alter_diplome_description_alter_diplome_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
