# Generated by Django 4.2.7 on 2023-12-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_alter_diplome_graduation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AddField(
            model_name='skill',
            name='logo',
            field=models.ImageField(blank=True, upload_to='static/media/skill_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/media/project_images/'),
        ),
    ]
