# Generated by Django 4.2.7 on 2023-12-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_category_rename_skill_skill_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='categorya',
            new_name='category',
        ),
    ]
