# Generated by Django 4.2.7 on 2023-12-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_rename_categorya_skill_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
