# Generated by Django 4.2.7 on 2023-12-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='static/media/project_images/')),
                ('description', models.TextField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('demo', models.URLField(blank=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='cv.profil')),
            ],
        ),
    ]
