# Generated by Django 4.2.7 on 2023-12-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0017_remove_theme_category_order_categoryorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='category_order',
            field=models.ManyToManyField(through='cv.CategoryOrder', to='cv.category'),
        ),
    ]
