# Generated by Django 4.2.9 on 2024-01-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0021_auto_20240112_1219.py'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplome',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diplome',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diplome',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diplome',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='poste_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='poste_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='intro_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='intro_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
