# Generated by Django 4.2.9 on 2024-01-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0029_auto_20240113_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='job_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='job_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
