# Generated by Django 4.2.9 on 2024-01-14 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0031_theme_skill_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='profil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='cv.profil'),
        ),
    ]
